spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:34.10.13.109}:${DB_PORT:5432}/${DB_NAME:postgres}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

grpc:
  server:
    port: ${GRPC_PORT:9091}

  client:
    trade-executor:
      address: ${TRADE_EXECUTOR_ADDRESS:dns:///trade-executor-service-1011460061885.us-central1.run.app:443}
      negotiationType: ${TRADE_EXECUTOR_NEGOTIATION_TYPE:TLS}
