services:

  postgres:
    image: postgres:14
    container_name: trading-postgres
    restart: always
    environment:
      POSTGRES_DB: tradingdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  order-service:
    build:
      context: .
      dockerfile: Dockerfile.order-service
    ports:
      - "9090:9090"
    depends_on:
      - matching-engine
      - postgres

  matching-engine:
    build:
      context: .
      dockerfile: Dockerfile.matching-engine
    ports:
      - "9091:9091"
    depends_on:
      - trade-executor-service
      - postgres

  trade-executor-service:
    build:
      context: .
      dockerfile: Dockerfile.trade-executor-service
    ports:
      - "9092:9092"
    depends_on:
      - ledger-service
      - postgres

  ledger-service:
    build:
      context: .
      dockerfile: Dockerfile.ledger-service
    ports:
      - "9093:9093"
    depends_on:
      - postgres

  portfolio-service:
    build:
      context: .
      dockerfile: Dockerfile.portfolio-service
    ports:
      - "9094:9094"
    depends_on:
      - ledger-service
      - postgres
