server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://34.10.13.109:5432/postgres
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

grpc:
  server:
    port: 9090

  client:
    matching-engine:
      # address: static://matching-engine:9091
      # negotiationType: plaintext
      address: dns:///matching-engine-1011460061885.us-central1.run.app:443
      negotiationType: TLS
