spring:
  datasource:
    url: jdbc:postgresql://34.10.13.109:5432/postgres
    username: postgres
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
grpc:
  server:
    port: 9094

  client:
    ledger-service:
      # address: static://ledger-service:9093
      # negotiationType: plaintext
      address: dns:///ledger-service-1011460061885.us-central1.run.app:443
      negotiationType: TLS
